version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/nk
    binary: nk
    ldflags:
      - -s -w -X github.com/sim4gh/nikte-cli/internal/cli.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: nikte
    repository:
      owner: sim4gh
      name: homebrew-nikte
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/sim4gh/nikte-cli"
    description: "Fast CLI for ephemeral content management"
    license: "MIT"
    install: |
      bin.install "nk"
    test: |
      system "#{bin}/nk", "--version"
